appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {m}\n"
  daily:
    kind: rolling_file
    path: "log/index.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {m}\n"
    filters:
      - kind: threshold
        level: warn
    policy:
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "log/index.{}.log"
        base: 0
        count: 10
root:
  level: info
  appenders:
    - stdout
    - daily