name: Build Index

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - name: Upload artifact
        uses: @actions/upload-artifact@v4
        with:
          name: geode-index
          path: ./target/aarch64-unknown-linux-gnu/release/geode-index
