name: Deploy Index

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install rust
        run: rustup toolchain install stable --profile minimal

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release

      - name: Install rsync
        run: sudo apt-get install rsync -y

      - name: Create ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.INDEX_SERVER }} > ~/.ssh/known_hosts

      - name: Upload target to server
        run: |
          rsync -avz target/release/geode-index ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }}:${{ secrets.INDEX_COPY_LOCATION }}

      - name: Run update script
        run: |
          ssh ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} ${{ secrets.INDEX_UPDATE_SCRIPT_PATH }}

      # - name: Push Docker image to index server
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/index_key
      #     chmod 600 ~/.ssh/index_key
      #     docker save geode-index:${{ env.RELEASE_VERSION }} | bzip2 | ssh -i ~/.ssh/index_key -o StrictHostKeyChecking=no ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} docker load

      # - name: Replace current deployment
      #   run: |
      #     ssh -i ~/.ssh/index_key -o StrictHostKeyChecking=no ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} "docker stop index && docker rm index && cd ${{ secrets.INDEX_DIR }} && \
      #     docker run --name=index --env-file=.env --restart=unless-stopped --network=index-net -p 3000:3000 -dit geode-index:${{ env.RELEASE_VERSION }}"
