name: Deploy Index

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install rust
        run: rustup toolchain install stable --profile minimal

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo check
          cargo build --release

      # - name: Push Docker image to index server
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/index_key
      #     chmod 600 ~/.ssh/index_key
      #     docker save geode-index:${{ env.RELEASE_VERSION }} | bzip2 | ssh -i ~/.ssh/index_key -o StrictHostKeyChecking=no ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} docker load

      # - name: Replace current deployment
      #   run: |
      #     ssh -i ~/.ssh/index_key -o StrictHostKeyChecking=no ${{ secrets.INDEX_USER }}@${{ secrets.INDEX_SERVER }} "docker stop index && docker rm index && cd ${{ secrets.INDEX_DIR }} && \
      #     docker run --name=index --env-file=.env --restart=unless-stopped --network=index-net -p 3000:3000 -dit geode-index:${{ env.RELEASE_VERSION }}"
